name: Notify Test

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "$(jq -n --arg actor "${{ github.actor }}" \
                        --arg branch "${{ github.ref_name }}" \
                        --arg msg "${{ github.event.head_commit.message }}" \
                        '{content: "\($actor)さんが \($branch) ブランチにpushしました。message: \($msg)"}')" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}