name: Notify Test

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "テストメッセージ"}' ${{ secrets.DISCORD_WEBHOOK_URL }}